export {default as App} from './App'
export {default as Register} from './Register'
export {default as Header} from './Header'
export {default as Login} from './Login'
export {default as Routines} from './Routines'
export {default as Activities} from './Activities'
export {default as CreateRoutine} from './CreateRoutine'
export {default as MyRoutines} from './MyRoutines'
// export {default as CreateActivity} from './CreateActivity'
// export {default as RemoveActivityOnRoutine} from './RemoveActivity'
// export {default as UpdateActivityOnRoutine} from './UpdateActivityonRoutine'
// export {default as AddActivityOnRoutine} from './AddActivityonRoutine'
export {default as EditRoutine} from './EditRoutine'
export {default as DeleteRoutine} from './DeleteRoutine'
